---
- name: Install tomcat8 and tomcat8-admin
  apt:
   name: "{{item.a}}"
   state: "{{item.b}}"
   update_cache: "{{item.c}}"
  with_items:
   - {a: "{{pkg1}}",b: "{{state1}}",c: "{{cache1}}"}
   - {a: "{{pkg2}}",b: "{{state1}}",c: "{{cache2}}"}
